/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Duy Nin
 */
public class DoiMatKhau extends javax.swing.JFrame {

    /**
     * Creates new form DoiMatKhau
     */
    public DoiMatKhau() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    private static String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
    private static String url = "jdbc:sqlserver://localhost:1433;databaseName=QLDUAN1;encrypt=false";
    private static String user = "sa";
    private static String password = "123456";
    private int selectedRow = -1;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txttendangnhap = new javax.swing.JTextField();
        txtmatkhaucu = new javax.swing.JPasswordField();
        txtmatkhaumoi = new javax.swing.JPasswordField();
        txtmatkhaumoi2 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btndongy = new javax.swing.JButton();
        btnhuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("ĐỔI MẬT KHẨU");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 280, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Tên Đăng Nhập");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Mật khẩu cũ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\FPT polytechnic\\Anh Code\\chuc nang\\logoo.png")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 210, 120));

        txttendangnhap.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txttendangnhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 160, 30));

        txtmatkhaucu.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtmatkhaucu, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 170, 30));

        txtmatkhaumoi.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtmatkhaumoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 160, 30));

        txtmatkhaumoi2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtmatkhaumoi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 170, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Mật khẩu mới");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Nhập lại mật khẩu mới");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));

        btndongy.setBackground(new java.awt.Color(0, 102, 102));
        btndongy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btndongy.setForeground(new java.awt.Color(255, 255, 255));
        btndongy.setText("Đồng ý");
        btndongy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndongyActionPerformed(evt);
            }
        });
        jPanel1.add(btndongy, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, 30));

        btnhuy.setBackground(new java.awt.Color(0, 102, 102));
        btnhuy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnhuy.setForeground(new java.awt.Color(255, 255, 255));
        btnhuy.setText("Hủy");
        btnhuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhuyActionPerformed(evt);
            }
        });
        jPanel1.add(btnhuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndongyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndongyActionPerformed
        // TODO add your handling code here:
                doiMatKhau();
    }//GEN-LAST:event_btndongyActionPerformed

    private void btnhuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhuyActionPerformed
        // TODO add your handling code here:
        LoginJFrame login = new LoginJFrame();
        login.setVisible(true);
        DoiMatKhau.this.dispose();
    }//GEN-LAST:event_btnhuyActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void doiMatKhau() {
        String taiKhoan = txttendangnhap.getText();
        String matKhauHienTai = new String(txtmatkhaucu.getPassword());
        String matKhauMoi = new String(txtmatkhaumoi.getPassword());
        String xacNhanMatKhauMoi = new String(txtmatkhaumoi2.getPassword());

        // Kiểm tra mật khẩu mới và xác nhận mật khẩu mới
        if (!matKhauMoi.equals(xacNhanMatKhauMoi)) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập giống mật khẩu mới ");
            return;
        }

        // Kết nối đến cơ sở dữ liệu
        try (Connection connection = DriverManager.getConnection(url, user, password)) {
            // Kiểm tra mật khẩu hiện tại
            String sql = "SELECT * FROM Login WHERE Username = ? AND Password = ?";
            try (PreparedStatement statement = connection.prepareStatement(sql)) {
                statement.setString(1, taiKhoan);
                statement.setString(2, matKhauHienTai);

                try (ResultSet resultSet = statement.executeQuery()) {
                    if (!resultSet.next()) {

                        return;
                    }
                }
            }

            // Đổi mật khẩu mới
            sql = "UPDATE Login SET Password = ? WHERE Username = ?";
            try (PreparedStatement statement = connection.prepareStatement(sql)) {
                statement.setString(1, matKhauMoi);
                statement.setString(2, taiKhoan);
                statement.executeUpdate();
                JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công");
                txttendangnhap.setText("");
                txtmatkhaucu.setText("");
                txtmatkhaumoi.setText("");
                txtmatkhaumoi2.setText("");
            }
        } catch (SQLException e) {
            e.printStackTrace();

        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoiMatKhau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndongy;
    private javax.swing.JButton btnhuy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtmatkhaucu;
    private javax.swing.JPasswordField txtmatkhaumoi;
    private javax.swing.JPasswordField txtmatkhaumoi2;
    private javax.swing.JTextField txttendangnhap;
    // End of variables declaration//GEN-END:variables
}
