/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ui;
import com.mycompany.dao.HoaDonDao;
import com.mycompany.dao.NhanVienDao;
import com.mycompany.model.ConnectDB;
import com.mycompany.dao.SanPhamDao;
import com.mycompany.entity.XAuth;
import com.mycompany.entity.XDialog;
import com.mycompany.model.SanPham;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import com.mycompany.entity.Xdate;
import com.mycompany.model.HoaDon;
import com.mycompany.model.NhanVien;

/**
 *
 * @author Duy Nin
 */
public class HonDonJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuSysTem
     */
    public HonDonJFrame() {
        initComponents();
        tableModel = (DefaultTableModel) tblhoadon.getModel();
        loadToDataHoaDon();
        tableModel = (DefaultTableModel) tblhoadonchitiet.getModel();
        loadToDataHoaDonChiTiet();
        this.setLocationRelativeTo(null);
        this.startDongHo();
    }
    Connection connection = null;
    Statement st = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    DefaultTableModel tableModel = new DefaultTableModel();
 
    public void loadToDataHoaDon() {
        try {
            tableModel.setRowCount(0);
            connection = ConnectDB.getConnection();
            String sqlString = "SELECT hd.MaHoaDon, hd.NgayBan, hd.IDNhanVien, hd.IDKhachHang, hd.TinhTrangDonHang, hd.TinhTrangThanhToan, kh.HoVaTen, kh.DiaChi, kh.SDT, kh.Email "
                    + "FROM HoaDon hd JOIN KhachHang kh ON hd.IDKhachHang = kh.ID";
            st = connection.createStatement();
            rs = st.executeQuery(sqlString);
            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getString("MaHoaDon"));
                row.add(rs.getString("NgayBan"));
                row.add(rs.getString("DiaChi"));
                row.add(rs.getString("IDNhanVien"));
                row.add(rs.getString("IDKhachHang"));
                row.add(rs.getString("TinhTrangDonHang"));
                row.add(rs.getString("TinhTrangThanhToan"));
                tableModel.addRow(row);
            }
            tblhoadon.setModel(tableModel);
            connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void loadToDataHoaDonChiTiet() {
        try {
            tableModel.setRowCount(0);
            connection = ConnectDB.getConnection();
            String sqlString = "Select * from ChiTietHoaDon";
            st = connection.createStatement();
            rs = st.executeQuery(sqlString);
            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getString("IDHoaDon"));
                row.add(rs.getString("IDSanPham"));
                row.add(rs.getString("SoLuong"));
                row.add(rs.getString("Gia"));
                tableModel.addRow(row);
            }
            tblhoadonchitiet.setModel(tableModel);
            connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jtbhoadon = new javax.swing.JTabbedPane();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblhoadon = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        lbloclock = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnxoa = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblhoadonchitiet = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        jScrollPane2.setViewportView(jTree1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(0, 102, 102));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblhoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Hóa Đơn", "Ngày Bán", "Địa Chỉ", "Mã NV", "Mã KH", "Thông Tin Đơn Hàng", "Trạng Thái Thanh Toán"
            }
        ));
        tblhoadon.setSelectionForeground(new java.awt.Color(0, 102, 102));
        jScrollPane6.setViewportView(tblhoadon);

        jPanel12.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 819, 284));

        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(0, 102, 102));
        jButton11.setText("Xuất Hóa Đơn");
        jPanel12.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 500, 130, -1));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 102));
        jLabel20.setText("HÓA ĐƠN");
        jPanel12.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 252, 52));
        jPanel12.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 6, 207, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setText("CỬA HÀNG LINH KIỆN ĐIỆN TỬ");
        jPanel12.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 184, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("Địa chỉ: ");
        jPanel12.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        jLabel24.setText("QTSC9, Đ. Tô Ký, Q12. TPHCM");
        jPanel12.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("Số Điện Thoại:");
        jPanel12.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        jLabel26.setText("0123456789");
        jPanel12.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setText("Email:");
        jPanel12.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 43, -1));

        jLabel28.setText("shoplkdt@gmail.com");
        jPanel12.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        lbloclock.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbloclock.setForeground(new java.awt.Color(0, 102, 102));
        lbloclock.setText("00 : 00 : 00 AM");
        jPanel12.add(lbloclock, new org.netbeans.lib.awtextra.AbsoluteConstraints(932, 133, 122, -1));

        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel12.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 500, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\FPT polytechnic\\Anh Code\\chuc nang\\logoo.png")); // NOI18N
        jPanel12.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, -1));

        btnxoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnxoa.setForeground(new java.awt.Color(0, 102, 102));
        btnxoa.setText("Xóa");
        jPanel12.add(btnxoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, -1, -1));

        jtbhoadon.addTab("Danh Sách Hóa Đơn", jPanel12);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel13.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 206, -1));
        jPanel13.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 32, 43, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel32.setText("CỬA HÀNG LINH KIỆN ĐIỆN TỬ");
        jPanel13.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 6, -1, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel33.setText("Địa chỉ:");
        jPanel13.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 32, 43, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setText("Số Điện Thoại:");
        jPanel13.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 54, -1, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel35.setText("Email:");
        jPanel13.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 76, 43, -1));

        jLabel36.setText("QTCS9, Đ. Tô Ký, Quận 12, TP HCM");
        jPanel13.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 32, -1, -1));

        jLabel37.setText("0123456789");
        jPanel13.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 54, -1, -1));
        jPanel13.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(918, 470, 43, -1));

        jLabel39.setText("shoplkdt@gmail.com");
        jPanel13.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 76, -1, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 102, 102));
        jLabel40.setText("HÓA ĐƠN CHI TIẾT");
        jPanel13.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 158, -1, -1));

        tblhoadonchitiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Mã sản phẩm", "Số lượng", "Giá"
            }
        ));
        jScrollPane7.setViewportView(tblhoadonchitiet);

        jPanel13.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 228, 820, 233));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\FPT polytechnic\\Anh Code\\chuc nang\\logoo.png")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel13.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, -1));

        jtbhoadon.addTab("Hóa Đơn Chi Tiết", jPanel13);

        jTabbedPane1.addTab("Hóa Đơn", jtbhoadon);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        MenuSystems menu = new MenuSystems();
        menu.setVisible(true);
        HonDonJFrame.this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    public void startDongHo() {
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss a");
        new javax.swing.Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                lbloclock.setText(sdf.format(Xdate.now()));
            }
        }).start();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HonDonJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HonDonJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HonDonJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HonDonJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HonDonJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnxoa;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTree jTree1;
    private javax.swing.JTabbedPane jtbhoadon;
    private javax.swing.JLabel lbloclock;
    private javax.swing.JTable tblhoadon;
    private javax.swing.JTable tblhoadonchitiet;
    // End of variables declaration//GEN-END:variables
}
