/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ui;
import com.mycompany.model.ConnectDB;
import com.mycompany.dao.SanPhamDao;
import com.mycompany.model.SanPham;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import com.mycompany.entity.Xdate;

/**
 *
 * @author Duy Nin
 */
public class KhachHangJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuSysTem
     */
    public KhachHangJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        tableModel = (DefaultTableModel) tblkhachhang.getModel();
        loadToDataKhachHang();
    }
    Connection connection = null;
    Statement st = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    DefaultTableModel tableModel = new DefaultTableModel();
// Set form cho từng sản phẩm + hình ảnh



    


    // load nội dung từ sql sản phẩm cho bảng sản phâm
     public void setFormKhachHang(int current) {
        txtidkh.setText(tblkhachhang.getValueAt(current, 0).toString());
        txtnamekh.setText(tblkhachhang.getValueAt(current, 1).toString());
        txtdiachikh.setText(tblkhachhang.getValueAt(current, 2).toString());
        txtsdtkh.setText(tblkhachhang.getValueAt(current, 3).toString());
        txtemailkh.setText(tblkhachhang.getValueAt(current, 4).toString());
    }

// load sản phẩm cho bảng khách hàng

    public void loadToDataKhachHang() {
        String[] columnNames = {"ID", "Họ và tên", "Email", "SĐT", "Địa Chỉ"};
        DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0);
        try {
            tableModel.setRowCount(0);
            connection = ConnectDB.getConnection();
            String sqlString = "Select * from KhachHang";
            st = connection.createStatement();
            rs = st.executeQuery(sqlString);
            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getString("ID"));
                row.add(rs.getString("HoVaTen"));
                row.add(rs.getString("DiaChi"));
                row.add(rs.getString("SDT"));
                row.add(rs.getString("Email"));
                tableModel.addRow(row);
            }
            tblkhachhang.setModel(tableModel);
            connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
// load bảng hóa đơn


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jtbkhachhang = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtidkh = new javax.swing.JTextField();
        txtnamekh = new javax.swing.JTextField();
        txtdiachikh = new javax.swing.JTextField();
        txtsdtkh = new javax.swing.JTextField();
        txtemailkh = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblkhachhang = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        btnthemkh = new javax.swing.JButton();
        btnxoakh = new javax.swing.JButton();
        btnsuakh = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        btnlammoik = new javax.swing.JButton();

        jScrollPane2.setViewportView(jTree1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(0, 102, 102));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jtbkhachhang.setBackground(new java.awt.Color(255, 255, 255));
        jtbkhachhang.setForeground(new java.awt.Color(0, 102, 102));
        jtbkhachhang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));

        jLabel12.setText("ID:");

        jLabel13.setText("Họ và tên:");

        jLabel14.setText("Địa chỉ:");

        jLabel15.setText("SĐT");

        jLabel16.setText("Email");

        txtnamekh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamekhActionPerformed(evt);
            }
        });

        txtdiachikh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiachikhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtidkh)
                            .addComponent(txtdiachikh)
                            .addComponent(txtsdtkh)
                            .addComponent(txtemailkh, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtnamekh, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtidkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtnamekh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtdiachikh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtsdtkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtemailkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(183, Short.MAX_VALUE))
        );

        tblkhachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblkhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblkhachhangMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblkhachhang);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 102));
        jLabel19.setText("Tìm kiếm:");

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 102, 102));
        jButton7.setText("Search");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addContainerGap())
        );

        btnthemkh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnthemkh.setForeground(new java.awt.Color(0, 102, 102));
        btnthemkh.setText("Thêm");
        btnthemkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemkhActionPerformed(evt);
            }
        });

        btnxoakh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnxoakh.setForeground(new java.awt.Color(0, 102, 102));
        btnxoakh.setText("Xóa");
        btnxoakh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoakhActionPerformed(evt);
            }
        });

        btnsuakh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsuakh.setForeground(new java.awt.Color(0, 102, 102));
        btnsuakh.setText("Sửa");
        btnsuakh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuakhActionPerformed(evt);
            }
        });

        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        btnlammoik.setForeground(new java.awt.Color(0, 102, 102));
        btnlammoik.setText("Làm Mới");
        btnlammoik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlammoikActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnback)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnlammoik)
                        .addGap(32, 32, 32)
                        .addComponent(btnthemkh)
                        .addGap(33, 33, 33)
                        .addComponent(btnxoakh)
                        .addGap(31, 31, 31)
                        .addComponent(btnsuakh)))
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsuakh)
                    .addComponent(btnxoakh)
                    .addComponent(btnthemkh)
                    .addComponent(btnback)
                    .addComponent(btnlammoik))
                .addGap(40, 40, 40))
        );

        jtbkhachhang.addTab("DANHSACHKHACHHANG", jPanel7);

        jTabbedPane1.addTab("Khách Hàng", jtbkhachhang);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdiachikhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiachikhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdiachikhActionPerformed

    private void txtnamekhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamekhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamekhActionPerformed
    int row = 0;
    private void tblkhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblkhachhangMouseClicked
        // TODO add your handling code here:
        current = tblkhachhang.getSelectedRow();
        setFormKhachHang(current);
    }//GEN-LAST:event_tblkhachhangMouseClicked

    private void btnthemkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemkhActionPerformed
        // TODO add your handling code here:
        try {
            connection = ConnectDB.getConnection();
            String sqlString = "insert into KhachHang values(?,?,?,?,?)";
            ps = connection.prepareStatement(sqlString);
            ps.setString(1, txtidkh.getText());
            ps.setString(2, txtnamekh.getText());
            ps.setString(3, txtdiachikh.getText());
            ps.setString(4, txtsdtkh.getText());
            ps.setString(5, txtemailkh.getText());
            int result = ps.executeUpdate();
            if (result == 1) {
                JOptionPane.showMessageDialog(this, "Them Thanh Cong");
            } else {
                JOptionPane.showMessageDialog(this, "Them that bai");
            }
            loadToDataKhachHang();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnthemkhActionPerformed

    private void btnxoakhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoakhActionPerformed
        // TODO add your handling code here:
        try {
            connection = ConnectDB.getConnection();
            String sqlString = "delete from KhachHang where ID = ?";
            ps = connection.prepareStatement(sqlString);
            ps.setString(1, txtidkh.getText());
            int pscount = ps.executeUpdate();
            if (pscount == 1) {
                JOptionPane.showMessageDialog(this, "Xoa Thanh Cong");
            }
            connection.close();
            loadToDataKhachHang();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnxoakhActionPerformed

    private void btnsuakhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuakhActionPerformed
        // TODO add your handling code here:
        try {
            connection = ConnectDB.getConnection();
            String sqlString = "Update KhachHang set HoVaTen= ?,DiaChi= ?,SDT= ?,Email= ? where ID= ?";
            ps = connection.prepareStatement(sqlString);
            ps.setString(1, txtnamekh.getText());
            ps.setString(2, txtdiachikh.getText());
            ps.setString(3, txtsdtkh.getText());
            ps.setString(4, txtemailkh.getText());
            ps.setString(5, txtidkh.getText());
            int result = ps.executeUpdate();
            if (result == 1) {
                JOptionPane.showMessageDialog(this, "Update Thanh Cong");
            } else {
                JOptionPane.showMessageDialog(this, "Update that bai");
            }
            connection.close();
            loadToDataKhachHang();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnsuakhActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        MenuSystems menu = new MenuSystems();
        menu.setVisible(true);
        KhachHangJFrame.this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnlammoikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlammoikActionPerformed
        // TODO add your handling code here:
        txtidkh.setText("");
        txtnamekh.setText("");
        txtemailkh.setText("");
        txtsdtkh.setText("");
        txtdiachikh.setText("");
    }//GEN-LAST:event_btnlammoikActionPerformed
    int current = 0;
    private void Dangxuat() {
        LoginJFrame login = new LoginJFrame();
        login.setVisible(true);
        KhachHangJFrame.this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhachHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhachHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhachHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhachHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhachHangJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnlammoik;
    private javax.swing.JButton btnsuakh;
    private javax.swing.JButton btnthemkh;
    private javax.swing.JButton btnxoakh;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTree jTree1;
    private javax.swing.JTabbedPane jtbkhachhang;
    private javax.swing.JTable tblkhachhang;
    private javax.swing.JTextField txtdiachikh;
    private javax.swing.JTextField txtemailkh;
    private javax.swing.JTextField txtidkh;
    private javax.swing.JTextField txtnamekh;
    private javax.swing.JTextField txtsdtkh;
    // End of variables declaration//GEN-END:variables
}
